# Copyright (c) 2020 Bridg Inc. All rights reserved.
# @author Sohil Jain <sohil.jain@bridg.com>

##
# This file defines the serverless infrastructure on AWS for a Lambda function performing a data ingestion as a part of
# 'Dollar-general Transformer' data pipeline.
###
service: bridg-dg-transformer-function
description: 'AWS Lambda function performing dollar general data transformation step of "Data Pipeline"'
frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  stages:
    - development
    - production
  function_name:
    development: bridg-dg-transformer-dev
    production: bridg-dg-transformer-production
  AWS_REGION: ${env:AWS_DEFAULT_REGION}
  DEAD_LETTER_QUEUE: ${self:custom.function_name.${self:provider.stage}}-dead-letter-queue
  BRIDG_ENV_NAME: ${env:BRIDG_ENV_NAME}
  BRIDG_CONFIG_URL: ${env:BRIDG_CONFIG_URL}
  BRIDG_1_ACCOUNT: ${env:BRIDG_1_ACCOUNT}
  S3_BUCKET_RAW_DATA_1: ${env:S3_BUCKET_RAW_DATA_1} # Name not ARN
  SNS_TOPIC_ARN_1: ${env:SNS_TOPIC_ARN_1}-${self:provider.stage}
  SNS_TOPIC_ARN_2: ${env:SNS_TOPIC_ARN_2}
  security_group: ${env:SECURITY_GROUP, 'sg-0710b844e08d5cb2e'}
  SUBNET_A: ${env:SUBNET_A, 'subnet-051cad2b010989d3a'}
  SUBNET_B: ${env:SUBNET_B, 'subnet-06d4b6a3c6e279276'}
  SUBNET_C: ${env:SUBNET_C, 'subnet-08f6d84463db5e1f8'}
  BATCH_JOBNAME: ${env:BATCH_JOBNAME}
  BATCH_JOBQUEUE: ${env:BATCH_JOBQUEUE}
  BATCH_JOBDEFINITION: ${env:BATCH_JOBDEFINITION}
  ALERT_SNS_PARAM: ${env:ALERT_SNS_PARAM}

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  cfLogs: true
  description: 'AWS Lambda function performing dollar-general transformation step'
  memorySize: 512
  timeout: 600 # The default is 6
  region: ${self:custom.AWS_REGION}
  versionFunctions: false
  deploymentBucket: cdp.com.serverless.${self:custom.AWS_REGION}.deploys
  role: DollarGeneralTransformerRole
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DetachNetworkInterface"
        - "ec2:AttachNetworkInterface"
        - "ec2:DeleteNetworkInterface"
      Resource: "arn:aws:ec2:${self:custom.AWS_REGION}:*:*"
  vpc:
    securityGroupIds:
      - ${self:custom.security_group}
    subnetIds:
      - ${self:custom.SUBNET_A}
      - ${self:custom.SUBNET_B}
      - ${self:custom.SUBNET_C}

package:
  artifact: src/dg_transformer_prepare.zip

resources:
  Resources:
    DollarGeneralTransformerRole:
      Type: "AWS::IAM::Role"
      DeletionPolicy: Delete
      Properties:
        RoleName: DollarGeneralTransformerLambdaRole-${opt:stage}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - events.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        Policies:
          - PolicyName: DollarGeneralTransformerSchedulerPolicy-${opt:stage}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:GetLogEvents
                  Resource: "arn:aws:logs:${self:custom.AWS_REGION}:*:log-group:/aws/lambda/*:*:*"
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                    - lambda:GetFunction
                  Resource: "arn:aws:lambda:${self:custom.AWS_REGION}:*:function:${self:custom.function_name.${self:provider.stage}}"
                - Effect: Allow
                  Action:
                    - events:*
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - s3:*
                  Resource:
                    - "arn:aws:s3:::${self:custom.S3_BUCKET_RAW_DATA_1}/*"
                    - "arn:aws:s3:::${self:custom.S3_BUCKET_RAW_DATA_1}"
                - Effect: Allow
                  Action:
                    - batch:SubmitJob
                    - batch:ListJobs
                  Resource:
                    - "*" # Rights given to all resources because batch need permission to compute environment as well.
                - Effect: Allow
                  Action:
                    - elasticmapreduce:*
                  Resource: "*"  # Have not specified resource here because we start ephemeral cluster which terminates after job completion
                - Effect: Allow
                  Action:
                    - iam:PassRole
                  Resource:
                    - "arn:aws:iam::596832493770:role/EMR_DefaultRole"
                    - "arn:aws:iam::596832493770:role/EMR_EC2_DefaultRole"
                - Effect: Allow
                  Action:
                    - secretsmanager:*
                  Resource:
                    - "arn:aws:secretsmanager:us-west-2:596832493770:secret:/cdp/SecretManager/dollargeneral-transformer/-YjmQfu"
                - Effect: Allow
                  Action:
                    - ssm:GetParametersByPath
                    - ssm:GetParameters
                    - ssm:GetParameter
                  Resource:
                    - "arn:aws:ssm:us-west-2:596832493770:parameter/cdp/SNS/Alarm"
                - Effect: Allow
                  Action:
                    - SNS:Publish
                  Resource:
                    - "arn:aws:sns:us-west-2:596832493770:cdp-SNS-1XM4Q7BJBS0UB-AlarmTopic-GWQ3SR7P7LPY"


functions:
  DollarGeneralTransformer:
    name: ${self:custom.function_name.${self:provider.stage}}
    description: "AWS Lambda function performing dollar general transformation step of 'Data Pipeline'."
    handler: main/lambda_trigger_batch.lambda_handler
    events:
      - sns: ${self:custom.SNS_TOPIC_ARN_1}
      - sns: arn:aws:sns:us-west-2:992345807264:${self:custom.SNS_TOPIC_ARN_2} # Default data_ingestion_ftp_sync topic
    environment:
      S3_BUCKET_RAW_DATA_1: ${self:custom.S3_BUCKET_RAW_DATA_1}
      BATCH_JOBNAME: ${self:custom.BATCH_JOBNAME}
      BATCH_JOBQUEUE: ${self:custom.BATCH_JOBQUEUE}
      BATCH_JOBDEFINITION: ${self:custom.BATCH_JOBDEFINITION}
      ALERT_SNS_PARAM: ${self:custom.ALERT_SNS_PARAM}
      BRIDG_ENV_NAME: ${self:custom.BRIDG_ENV_NAME}
    tags:
      Environment: ${self:custom.BRIDG_ENV_NAME}
