# Copyright (c) 2020 Bridg Inc. All rights reserved.
# @author Sohil Jain <sohil.jain@bridg.com>

##
# This file defines the serverless infrastructure on AWS for a Lambda function performing a data ingestion as a part of
# 'Dollar-general Transformer' data pipeline.
###
service: bridg-dg-transformer-function
description: 'AWS Lambda function performing dollar general data transformation step of "Data Pipeline"'
frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  stages:
    - development
    - production
  function_name:
    development: bridg-dg-transformer
    production: bridg-dg-transformer
  AWS_REGION: ${env:AWS_DEFAULT_REGION}
  DEAD_LETTER_QUEUE: ${self:custom.function_name.${self:provider.stage}}-dead-letter-queue
  BRIDG_ENV_NAME: ${env:BRIDG_ENV_NAME}
  BRIDG_CONFIG_URL: ${env:BRIDG_CONFIG_URL}
  BRIDG_1_ACCOUNT: ${env:BRIDG_1_ACCOUNT}
  S3_BUCKET_RAW_DATA_1: ${env:S3_BUCKET_RAW_DATA_1} # Name not ARN
  SNS_TOPIC_ARN_1: ${env:SNS_TOPIC_ARN_1}
  SNS_TOPIC_ARN_2: ${env:SNS_TOPIC_ARN_2}
  security_group: ${env:SECURITY_GROUP, 'sg-0710b844e08d5cb2e'}
  SUBNET_A: ${env:SUBNET_A, 'subnet-051cad2b010989d3a'}
  SUBNET_B: ${env:SUBNET_B, 'subnet-06d4b6a3c6e279276'}
  SUBNET_C: ${env:SUBNET_C, 'subnet-08f6d84463db5e1f8'}

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  cfLogs: true
  description: 'AWS Lambda function performing dollar-general transformation step'
  memorySize: 512
  timeout: 600 # The default is 6
  region: ${self:custom.AWS_REGION}
  versionFunctions: false
  deploymentBucket: ${env:BRIDG_ENV_NAME}.com.serverless.${self:custom.AWS_REGION}.deploys
  role: dGTransformerRole
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DetachNetworkInterface"
        - "ec2:AttachNetworkInterface"
        - "ec2:DeleteNetworkInterface"
      Resource: "arn:aws:ec2:${self:custom.AWS_REGION}:*:*"
  vpc:
    securityGroupIds:
      - ${self:custom.security_group}
    subnetIds:
      - ${self:custom.SUBNET_A}
      - ${self:custom.SUBNET_B}
      - ${self:custom.SUBNET_C}

package:
  artifact: build/dg_transformer_prepare.zip

resources:
  Resources:
    DGTransformerRole:
      Type: "AWS::IAM::Role"
      DeletionPolicy: Delete
      Properties:
        RoleName: DGTransformerLambdaRole-${opt:stage}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - events.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        Policies:
          - PolicyName: DGTransformerSchedulerPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:GetLogEvents
                  Resource: "arn:aws:logs:${self:custom.AWS_REGION}:*:log-group:/aws/lambda/*:*:*"
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                    - lambda:GetFunction
                  Resource: "arn:aws:lambda:${self:custom.AWS_REGION}:*:function:${self:custom.function_name.${self:provider.stage}}"
                - Effect: Allow
                  Action:
                    - events:*
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - s3:*
                  Resource:
                    - "arn:aws:s3:::${self:custom.S3_BUCKET_RAW_DATA_1}/*"
                    - "arn:aws:s3:::${self:custom.S3_BUCKET_RAW_DATA_1}"

functions:
  DGTransformer:
    name: ${self:custom.function_name.${self:provider.stage}}
    description: "AWS Lambda function performing dollar generaal transformation step of 'Data Pipeline'."
    handler: main.lambda_trigger_batch.lambda_handler
    events:
      - sns: ${self:custom.SNS_TOPIC_ARN_1}
    environment:
      BRIDG_ENV_NAME: ${self:custom.BRIDG_ENV_NAME}
      BRIDG_CONFIG_URL: ${self:custom.BRIDG_CONFIG_URL}
    tags:
      Environment: ${self:custom.BRIDG_ENV_NAME}
