# Copyright (c) 2021 Bridg Inc. All rights reserved.
# @author Sohil Jain <sohil.jain@bridg.com>

bucket: dev-cdp-data-lake
s3a_bucket: s3a://dev-cdp-data-lake
s3_staging_path: dollargeneral/transformed/staging
s3_staging_path_1010: dollargeneral-popshelf/transformed/staging/1010
s3_tmp_path: dollargeneral-popshelf/transformed/temp
s3_gold_path: dollargeneral-popshelf/transformed/gold
s3_archive_path: dollargeneral-popshelf/transformed/archive
remote_1010_path: dollargeneral-popshelf/1010/Daily
s3_staging_path_weekly_1010: dollargeneral-popshelf/weekly_transformed/staging/1010
s3_archive_path_weekly: dollargeneral-popshelf/weekly_transformed/archive
remote_Aurus_path: dollargeneral/Aurus/Daily
local_Path: Documents/DG
secret: /dev-cdp/SecretManager/dollargeneral-transformer/
aurus_startdate: '99990101'


table_queries:

  organization: "select dgorg.*,
  dt as partition_col from dg_organization dgorg"

  transactions: "select dgtrans.*,
  concat(dgtrans.sourcetransactionnumber, '~', dgtrans.postransactionnumber , '~' ,dgtrans.registernumber) check_id,
  dt as partition_col
  from dg_transactions dgtrans"

  tenders: "with dgaur as (select store_id,
    store_id,
    to_date(left(store_transaction_date_time,10),'M/dd/yyyy') dgaur_date,
    masked_card_number,
    approved_amount,
    pos_register_number,
    min(customer_name) as customer_name
 from dg_aurus group by 1,2,3,4,5,6)
select dgtrans.sourcecustomernumber, dgtrans.registernumber, dgtrans.transactiontimestamp, dgtrans.currency,
dgaur.customer_name, concat(dgtndrs.sourcetransactionnumber, '~', dgtrans.postransactionnumber , '~' ,dgtrans.registernumber) check_id,
dgtndrs.sourcetransactionnumber, dgtndrs.sourceorganizationnumber, dgtndrs.transactiondate, dgtndrs.tendercode,
dgtndrs.tendername, dgtndrs.tenderamt, dgtndrs.accountnumbermasked,dgtndrs.cardusagetype, dgtndrs.dt,
dgtndrs.dt as partition_col
from dg_tenders dgtndrs
join dg_transactions dgtrans
    on dgtndrs.dt=dgtrans.dt
    and dgtndrs.sourcetransactionnumber = dgtrans.sourcetransactionnumber
    and dgtndrs.sourceorganizationnumber = dgtrans.sourceorganizationnumber
    and dgtndrs.transactiondate = dgtrans.datecreated
left join dgaur
    on dgaur.store_id = dgtndrs.sourceorganizationnumber
    and cast(dgaur.pos_register_number as integer)=cast(dgtrans.registernumber as integer)
    and dgaur.dgaur_date = dgtndrs.transactiondate
    and substring(dgaur.masked_card_number,-4) = substring(dgtndrs.accountnumbermasked,-4)
    and substring(dgaur.masked_card_number,1,6) = substring(dgtndrs.accountnumbermasked,1,6)
    and dgaur.approved_amount = dgtndrs.tenderamt
"

  transaction_item: "
    select dgtrnitem.*, concat(dgtrnitem.sourcetransactionnumber, '~', dgtrans.postransactionnumber , '~' ,dgtrans.registernumber) check_id,
    dgtrans.transactiontimestamp, dgtrnitem.dt as partition_col
    from dg_transaction_item dgtrnitem join dg_transactions dgtrans
    on dgtrnitem.dt=dgtrans.dt
    and dgtrnitem.sourcetransactionnumber = dgtrans.sourcetransactionnumber
    and dgtrnitem.sourceorganizationnumber =dgtrans.sourceorganizationnumber
    and dgtrnitem.datecreated = dgtrans.datecreated
    "

  discounts: "
    with dgdisc as (select distinct discountcode, DiscountDescription, DiscountType, dt from dg_discounts)
    select
    dgtrnitem.DateCreated, dgtrnitem.SourceTransactionNumber, dgtrnitem.SourceTransactionItemNumber, dgtrnitem.SourceOrganizationNumber, dgtrnitem.InvoiceDate,
    dgtrnitem.ShipDate, dgtrnitem.SourceProductNumber, dptrnxref.DiscountCode, dptrnxref.DiscountAmt, dgdisc.DiscountType, dgdisc.DiscountDescription,
    concat(dgtrnitem.sourcetransactionnumber, '~', dgtrans.postransactionnumber , '~' ,dgtrans.registernumber) check_id, dptrnxref.dt,
    dgtrnitem.dt as partition_col
    from dg_trans_disc_xref dptrnxref join dg_transaction_item dgtrnitem
    on  dptrnxref.dt=dgtrnitem.dt and
        dptrnxref.SourceTransactionItemNumber = dgtrnitem.SourceTransactionItemNumber
    join dg_transactions dgtrans on dptrnxref.dt=dgtrans.dt
        and dgtrnitem.Sourcetransactionnumber = dgtrans.Sourcetransactionnumber
        and dgtrnitem.sourceorganizationnumber = dgtrans.sourceorganizationnumber
        and dgtrnitem.datecreated = dgtrans.datecreated
    join dgdisc on dptrnxref.dt=dgdisc.dt
        and dptrnxref.discountcode = dgdisc.discountcode"

  product_category: "
select dgprodcatg.*, dt as partition_col
from dg_product_category dgprodcatg"


  product: "
select dgprod.*, dgprodcatg.Name as Sourceproductcategoryname, dgprod.dt as partition_col
from dg_product dgprod join dg_product_category dgprodcatg
on dgprod.dt=dgprodcatg.dt
and dgprod.Sourceproductcategorynumber = dgprodcatg.Sourcecategorynumber
and dgprod.datecreated= dgprodcatg.datecreated"

cols :
    organization : ['Sourceorganizationnumberkey',
                            'Name',
                            'Status',
                            'Type',
                            'Subtype',
                            'Parentsourceorganizationnumber',
                            'Country',
                            'State',
                            'City',
                            'Addr_line_1',
                            'Addr_line_2',
                            'Zip',
                            'Excludeascloseststore',
                            'Datecreated',
                            'Customattributes',
                            'dt']

    discounts:  ['DateCreated',
                         'SourceTransactionNumber',
                         'SourceTransactionItemNumber',
                         'SourceOrganizationNumber',
                         'InvoiceDate',
                         'ShipDate',
                         'SourceProductNumber',
                         'DiscountCode',
                         'DiscountAmt',
                         'DiscountType',
                         'DiscountDescription',
                         'check_id',
                         'dt']

    product_category: ['Sourcecategorynumber',
                                'Name',
                                'Sourceparentcategorynumber',
                                'Datecreated',
                                'Customattributes',
                                'dt']

    product: ['Sourceproductnumber',
                       'Name',
                       'Description',
                       'Producturl',
                       'Imageurl',
                       'Parentproductnumber',
                       'BrandName',
                       'Msrp',
                       'Listprice',
                       'Saleprice',
                       'Salecondition',
                       'Availability',
                       'Availableqty',
                       'Recostatus',
                       'Size',
                       'Color',
                       'Sourceproductcategorynumber',
                       'Datecreated',
                       'Customattributes',
                       'dt',
                       'Sourceproductcategoryname']

    transactions : ['sourcetransactionnumber',
                            'SourceOrganizationNumber',
                            'Total',
                            'Currency',
                            'Discount',
                            'Tax',
                            'Type',
                            'Transactiontimestamp',
                            'Sourcecustomernumber',
                            'DateCreated',
                            'CustomAttributes',
                            'Promoamt',
                            'Couponamt',
                            'Posdiscamt',
                            'Manufacturercouponamt',
                            'registernumber',
                            'AccountNumberMasked',
                            'postransactionnumber',
                            'dt',
                            'check_id']

    tenders: ['sourcecustomernumber',
                       'registernumber',
                       'transactiontimestamp',
                       'currency',
                       'customer_name',
                       'check_id',
                       'sourcetransactionnumber',
                       'sourceorganizationnumber',
                       'transactiondate',
                       'tendercode',
                       'tendername',
                       'tenderamt',
                       'accountnumbermasked',
                       'cardusagetype',
                       'dt']

    line_item: ['Sourcetransactionitemnumber',
                         'Sourcetransactionnumber',
                         'SourceOrganizationNumber',
                         'Type',
                         'Subtype',
                         'Invoicedate',
                         'Shipdate',
                         'Sourceproductnumber',
                         'Quantity',
                         'Weight',
                         'Volume',
                         'Listprice',
                         'Currency',
                         'Salesrevenue',
                         'Discount',
                         'Costbasis',
                         'Tax',
                         'Shippingrevenue',
                         'Shippingcost',
                         'Shippingdiscount',
                         'Otherrevenue',
                         'Othercosts',
                         'datecreated',
                         'dt',
                         'check_id',
                         'transactiontimestamp']
