# Copyright (c) 2021 Bridg Inc. All rights reserved.
# @author Sohil Jain <sohil.jain@bridg.com>

Name: backfill-cdp-dg-transformer-daily-emr-cluster
LogUri: "s3://dev-cdp-logs-bucket/dollargeneral/"
ReleaseLabel: "emr-6.4.0"
Applications:
    - Name: "Spark"
Configurations:
    - Classification: spark-env
      Configurations:
        - Classification: export
          Properties:
            PYSPARK_PYTHON: "/usr/bin/python3"
            ALERT_SNS_PARAM: "/dev-cdp/SNS/Alarm"
            ALERT_SNS_ARN: "arn:aws:sns:us-west-2:020970917333:devops-alerts-dev"

Instances:
    HadoopVersion: Amazon 2.8.5
    InstanceGroups:
    - Name: Master nodes
      Market: ON_DEMAND
      InstanceRole: MASTER
      InstanceType: m6g.4xlarge
      InstanceCount: 1
      EbsConfiguration:
        EbsBlockDeviceConfigs:
        - VolumeSpecification:
            VolumeType: gp2
            SizeInGB: 20
          VolumesPerInstance: 1
        EbsOptimized: True
    - Name: Slave nodes
      Market: ON_DEMAND
      InstanceRole: CORE
      InstanceType: r5.4xlarge
      InstanceCount: 1
      EbsConfiguration:
        EbsBlockDeviceConfigs:
        - VolumeSpecification:
            VolumeType: gp2
            SizeInGB: 100
          VolumesPerInstance: 1
        EbsOptimized: True
    - Name: Slave nodes
      Market: ON_DEMAND
      InstanceRole: TASK
      InstanceType: r5.4xlarge
      InstanceCount: 2
      EbsConfiguration:
        EbsBlockDeviceConfigs:
        - VolumeSpecification:
            VolumeType: gp2
            SizeInGB: 100
          VolumesPerInstance: 1
        EbsOptimized: True
    Ec2KeyName: towerbridg
    KeepJobFlowAliveWhenNoSteps: False
    TerminationProtected: False
    Ec2SubnetId: subnet-01d153dc6df563b60
Steps:
    - Name: transformer-step-1
      ActionOnFailure: TERMINATE_CLUSTER
      HadoopJarStep:
        Properties:
        - Key: PYSPARK_PYTHON
          Value: "/usr/bin/python3"
        Jar: command-runner.jar
        Args:
        - sudo
        - pip3
        - install
        - boto3
    - Name: transformer-step-2
      ActionOnFailure: TERMINATE_CLUSTER
      HadoopJarStep:
        Properties:
        - Key: PYSPARK_PYTHON
          Value: "/usr/bin/python3"
        Jar: command-runner.jar
        Args:
        - spark-submit
        - --py-files
        - s3://towerbridg-binary-registry/bridg-dollargeneral-transformer/dg_transformer_prepare.zip
        - s3://towerbridg-binary-registry/bridg-dollargeneral-transformer/main/run.py
        - --module
        - emr_process_gold
        - --env
        - backfill
        - --root-dir
        - s3://towerbridg-binary-registry/bridg-dollargeneral-transformer
        - --type
        - dg
        - --schedule
        - daily
VisibleToAllUsers: True
JobFlowRole: "EMR_EC2_DefaultRole"
ServiceRole: "EMR_DefaultRole"
ScaleDownBehavior: "TERMINATE_AT_TASK_COMPLETION"
